FROM ubuntu:xenial
WORKDIR /usr/local
RUN 	apt-get update && \
	echo "update ok" && \
	apt-get install openjdk-8-jdk:amd64 -y && \
	echo "java ok" && \
	apt-get install git -y && \
	echo "git ok" && \
	apt-get install wget -y && \
	echo "wget ok"
	
